config/routes.rb
Kikuria::Application.routes.draw do
  resources :audios

  get "static_pages/home"

  get "static_pages/search"

  get "static_pages/help"

  resources :comments

  devise_for :users
  resources  :users, :only => [:show]

  resources :lexemes, :syntagms do
    collection do
      get 'search'
      get 'searchform'
      get 'export_csv'
    end
    resources :comments
  end

    
  root :to => "static_pages#home"

end

app/models/audio.rb
class Audio < ActiveRecord::Base
  belongs_to :user
  has_many :lexemes
  has_many :syntagms
end

app/controllers/audios_controller.rb
class AudiosController < ApplicationController
  # GET /audios
  # GET /audios.json
  def index
    @audios = Audio.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @audios }
    end
  end

  # GET /audios/1
  # GET /audios/1.json
  def show
    @audio = Audio.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @audio }
    end
  end

  # GET /audios/new
  # GET /audios/new.json
  def new
    @audio = Audio.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @audio }
    end
  end

  # GET /audios/1/edit
  def edit
    @audio = Audio.find(params[:id])
  end

  # POST /audios
  # POST /audios.json
  def create
    @audio = Audio.new(params[:audio])

    respond_to do |format|
      if @audio.save
        format.html { redirect_to @audio, notice: 'Audio was successfully created.' }
        format.json { render json: @audio, status: :created, location: @audio }
      else
        format.html { render action: "new" }
        format.json { render json: @audio.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /audios/1
  # PUT /audios/1.json
  def update
    @audio = Audio.find(params[:id])

    respond_to do |format|
      if @audio.update_attributes(params[:audio])
        format.html { redirect_to @audio, notice: 'Audio was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @audio.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /audios/1
  # DELETE /audios/1.json
  def destroy
    @audio = Audio.find(params[:id])
    @audio.destroy

    respond_to do |format|
      format.html { redirect_to audios_url }
      format.json { head :ok }
    end
  end
end

app/helpers/audios_helper.rb
module AudiosHelper
end

app/views/audios/_form.html.erb
<%= form_for(@audio) do |f| %>
  <% if @audio.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@audio.errors.count, "error") %> prohibited this audio from being saved:</h2>

      <ul>
      <% @audio.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :link %><br />
    <%= f.text_field :link %>
  </div>
  <div class="field">
    <%= f.label :notes %><br />
    <%= f.text_area :notes %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/audios/edit.html.erb
<h1>Editing audio</h1>

<%= render 'form' %>

<%= link_to 'Show', @audio %> |
<%= link_to 'Back', audios_path %>

app/views/audios/index.html.erb
<h1>Listing audios</h1>

<table>
  <tr>
    <th>Description</th>
    <th>Link</th>
    <th>Notes</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @audios.each do |audio| %>
  <tr>
    <td><%= audio.description %></td>
    <td><a href="<%= audio.link %>">Location</a></td>
    <td><%= audio.notes %></td>
    <td><%= link_to 'Show', audio %></td>
    <td><%= link_to 'Edit', edit_audio_path(audio) %></td>
    <td><%= link_to 'Destroy', audio, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Audio', new_audio_path %>

app/views/audios/new.html.erb
<h1>New audio</h1>

<%= render 'form' %>

<%= link_to 'Back', audios_path %>

app/views/audios/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Description:</b>
  <%= @audio.description %>
</p>

<p>
  <b>Link:</b>
  <a href="<%= @audio.link %>"><%= @audio.link %></a>
</p>

<p>
  <b>Notes:</b>
  <%= @audio.notes %>
</p>


<%= link_to 'Edit', edit_audio_path(@audio) %> |
<%= link_to 'Back', audios_path %>