config/routes.rb
Kikuria::Application.routes.draw do
  resources :audios

  get "static_pages/home"

  get "static_pages/search"

  get "static_pages/help"

  resources :comments

  devise_for :users
  resources  :users, :only => [:show]

  resources :lexemes, :syntagms do
    collection do
      get 'search'
      get 'searchform'
      get 'export_csv'
    end
    resources :comments
  end

    
  root :to => "static_pages#home"

end

app/models/lexeme.rb
# encoding: UTF-8

class Lexeme < ActiveRecord::Base
  belongs_to :user

  belongs_to :audio
  has_many :comments, :as => :commentable

  validates :root, :presence => true
  validates :gloss, :presence => true

  def Lexeme.toOrth(item)
=begin
#I wish Ruby had Python's unit test stuff.
Lexeme.toOrth("omorronyong'chjo")
 => "omoRo9oNcyo" 
=end
    #translates non-standard (relative to Jeremy :D) symbols to Jeremy's preferred monograph-only orthography.
    #rr -> R; ñ ny -> 9; ng' -> N; ch -> c; j -> y
    subpairs = []
    subpairs << ["rr", "R"]
    subpairs << ["ny", "9"]
    subpairs << ["ñ", "9"]
    subpairs << ["ng'", "N"]
    subpairs << ["ch", "c"]
    subpairs << ["j", "y"]
    subpairs << ["β","b"]
    subpairs << ["ɣ","g"]
    subpairs << ["ɾ","r"]
    subpairs << ["r","R"]
    subpairs << ["t͡ʃ","c"]
    subpairs << ["ɲ","9"]
    subpairs << ["ŋ","N"]
    subpairs << ["j","y"]
    subpairs << ["ɪ","I"]
    subpairs << ["ʊ","U"]
    subpairs << ["ɛ","E"]
    subpairs << ["ɔ","O"]

    subpairs.each do |subpair|
        item = item.gsub(subpair[0], subpair[1])
    end
    return item
  end

  def Lexeme.toDisplayOrth(item, prefs)
    #convert a lexeme's stored representation (in Jeremy's preferred orthography) to arbitrary orthography.
    #prefs is a hash with members :trill, :palatalnasal, :velarnasal, :palatalaffricate, :palatalglide
  
    #sets defaults
    prefs[:trill] = "R" if !prefs[:trill]
    prefs[:palatalnasal] = "9" if !prefs[:palatalnasal]
    prefs[:velarnasal] = "N" if !prefs[:velarnasal]
    prefs[:palatalaffricate] = "c" if !prefs[:palatalaffricate]
    prefs[:palatalglide] = "y" if !prefs[:palatalglide]
    
    return item.gsub("R", prefs[:trill]).gsub("9", prefs[:palatalnasal]).gsub("N", prefs[:velarnasal]).gsub("c", prefs[:palatalaffricate]).gsub("y", prefs[:palatalglide])
  end

  def toOrth(item) #for backwards compatibility
    return Lexeme.toOrth(item)
  end
  def toDisplayOrth(item, prefs)
    return Lexeme.toDisplayOrth(item, prefs)
  end

  #xml = Nokogiri::XML(File.read('http://linguistics-ontology.org/gold-2010.xml'))
  #partOfSpeechNodes = doc.xpath('//concept[@parent="http://purl.org/linguistics/gold/PartOfSpeechProperty"]/label')
  #partsOfSpeech = []
  #partOfSpeechNodes.each do |node|
  #  partsOfSpeech << node.text
  #end
  def Lexeme.partsOfSpeech
    #you might need to customize this for languages other than Kikuria.
    return ["Adjective", "Adverb", "NegationOperator", "Noun", "Preposition", "Pronoun", "Quantifier", "Verb"]
  end
  def Lexeme.translateToGold(elem)
    if elem == "Pronoun"
        return "Pronominal"
    elsif elem == "Verb"
        return "Verbal"
    elsif elem == "v"
        return "Verbal"
    elsif elem == "n"
        return "Noun"
    elsif elem == "Adjective"
        return "Adjectival"
    elsif elem == "Adverb"
        return "Adverbial"
    elsif elem == "TomorrowFutureTense"
        return "CrastinalFutureTense"
    elsif elem == "YesterdayPastTense"
        return "HesternalPastTense"
    elsif elem == "TodayPastTense"
        return "HodiernalPastTense"
    elsif elem == "TodayFutureTense"
        return "HodiernalFutureTense"
    elsif Lexeme.partsOfSpeech.include? elem or Lexeme.tenses.include? elem
        return elem
    else
        raise ArgumentError, "I don't know what " + elem + " is!"
    end
  end

  def Lexeme.tenses
    #You'll definitely need to customize this for other languages!
    return ["RemoteFutureTense", "TomorrowFutureTense", "TodayFutureTense", "TodayPastTense", "PresentTense", "YesterdayPastTense", "RemotePastTense",]
  end

end

app/controllers/lexemes_controller.rb
# encoding: UTF-8

class LexemesController < ApplicationController
  #before_filter :authenticate_user!, :only => [:create, :edit, :update, :destroy, :new]
  load_and_authorize_resource

  require 'csv'

  # GET /lexemes
  # GET /lexemes.json
  def index
    @lexemes = Lexeme.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @lexemes }
    end
  end

  # GET /lexemes/1
  # GET /lexemes/1.json
  def show
    @lexeme = Lexeme.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @lexeme }
    end
  end



  def search
    @matches = []
    regex = params[:regex]
    @regex = regex
    regex = regex.gsub("C", "[bcdghjklmnN9rRstwy]")
    regex = regex.gsub("V", "[aeiouEIOU]")

    fields = [params[:field]]
    if fields == ['all']
        fields = ['sgNounClassMorpheme', 'plNounClassMorpheme', 'root', 'sgTranscription', 'plTranscription']
    end
    
    Lexeme.all.each do |lexeme|
        regexp = Regexp.new(lexeme.toOrth(regex))
        fields.each do |field|
            @matches << lexeme if regexp.match(lexeme[field]) and !@matches.include?(lexeme)
        end
        #@nonmatches << lexeme unless Regexp.new(params[:regex]).match(lexeme.token)
    end

    respond_to do |format|
      format.html # search.html.erb
      format.json { render json: @matches }
    end
  end

  # GET /lexemes/new
  # GET /lexemes/new.json
  def new
    @lexeme = Lexeme.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @lexeme }
    end
  end

  # GET /lexemes/1/edit
  def edit
    @lexeme = Lexeme.find(params[:id])
  end

  # POST /lexemes
  # POST /lexemes.json
  def create

    @lexeme = Lexeme.new(params[:lexeme])

    @lexeme.editDate = Time.now
    
    @lexeme.audio = Audio.find(params[:audio]) unless params[:audio].nil? or params[:audio] == ""
    
    [:root, :sgNounClassMorpheme, :plNounClassMorpheme].each do |item|
        @lexeme[item] = @lexeme.toOrth(@lexeme[item])
    end
    @lexeme.sgTranscription = @lexeme.sgNounClassMorpheme + @lexeme.root unless (@lexeme.sgNounClassMorpheme.nil? or @lexeme.sgNounClassMorpheme == "")
    @lexeme.plTranscription = @lexeme.plNounClassMorpheme + @lexeme.root unless (@lexeme.plNounClassMorpheme.nil? or @lexeme.plNounClassMorpheme == "")

    current_user.lexemes << @lexeme

    respond_to do |format|
      if @lexeme.save
        format.html { redirect_to lexemes_path, notice: 'Lexeme was successfully created.' }
        format.json { render json: @lexeme, status: :created, location: @lexeme }
      else
        format.html { render action: "new" }
        format.json { render json: @lexeme.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /lexemes/1
  # PUT /lexemes/1.json
  def update
    @lexeme = Lexeme.find(params[:id])
    
    updated_lexeme = params[:lexeme]

    @lexeme.editDate = Time.now
    @lexeme.audio = Audio.find(params[:audio]) unless params[:audio].nil? or params[:audio] == ""

    sgNounClassMorpheme = updated_lexeme[:sgNounClassMorpheme] or @lexeme.sgNounClassMorpheme
    plNounClassMorpheme = updated_lexeme[:plNounClassMorpheme] or @lexeme.plNounClassMorpheme
    root = updated_lexeme[:root] or @lexeme.root
    
    updated_lexeme[:sgTranscription] = sgNounClassMorpheme + root unless (sgNounClassMorpheme.nil? or sgNounClassMorpheme == "")
    updated_lexeme[:plTranscription] = plNounClassMorpheme + root unless (plNounClassMorpheme.nil? or plNounClassMorpheme == "")

    respond_to do |format|
      if @lexeme.update_attributes(updated_lexeme)
        format.html { redirect_to @lexeme, notice: 'Lexeme was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @lexeme.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lexemes/1
  # DELETE /lexemes/1.json
  def destroy
    @lexeme = Lexeme.find(params[:id])
    @lexeme.destroy

    respond_to do |format|
      format.html { redirect_to lexemes_url }
      format.json { head :ok }
    end
  end

  # adapted from http://oldwiki.rubyonrails.org/rails/pages/HowtoExportDataAsCSV
  # and http://www.funonrails.com/2012/01/csv-file-importexport-in-rails-3.html
  def export_csv
    filename = "Kikuria_lexemes"    

    #this is required if you want this to work with IE		
    if request.env['HTTP_USER_AGENT'] =~ /msie/i
      headers['Pragma'] = 'public'
      headers["Content-type"] = "text/plain"
      headers['Cache-Control'] = 'no-cache, must-revalidate, post-check=0, pre-check=0'
      headers['Content-Disposition'] = "attachment; filename=\"#{filename}\""
      headers['Expires'] = "0"
    end

    lexemes = Lexeme.find(:all)
    csv_data = CSV.generate do |csv|
      csv << ["token","gloss","pos","root","sgNounClassMorpheme", "sgNounClassNumber", "plNounClassNumber", "classOrGroup", "transcription", "editDate", "sgTranscription", "plTranscription","infTranscription", "additionalForms", "notes", "created_at", "updated_at", "plNounClassMorpheme", "user_id", "basicWord"]
      lexemes.each do |l|
        csv << [l.token, l.gloss, l.pos, l.root, l.sgNounClassMorpheme, l.sgNounClassNumber, l.plNounClassNumber, l.classOrGroup, l.transcription, l.editDate, l.sgTranscription, l.plTranscription, l.infTranscription, l.additionalForms, l.notes, l.created_at, l.updated_at, l.plNounClassMorpheme, l.user_id, l.basicWord]
      end
    end
    send_data csv_data,
      :type => 'text/csv; charset=iso-8859-1; header=present',
      :disposition => "attachment; filename=#{filename}.csv"
  end

end

app/helpers/lexemes_helper.rb
module LexemesHelper
end

app/views/lexemes/_form.html.erb
<%= form_for(@lexeme) do |f| %>
  <% if @lexeme.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@lexeme.errors.count, "error") %> prohibited this lexeme from being saved:</h2>

      <ul>
      <% @lexeme.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="grouping">
    <div class="field smalltoken">
      <%= f.label :sgNounClassMorpheme, "Singular noun class morpheme (if relevant)" %><br />
      <%= f.text_field :sgNounClassMorpheme %>
    </div>
    <div class="field" style="display: none;">
      <%= f.label :sgNounClassNumber %><br />
      <%= f.text_field :sgNounClassNumber %>
    </div>
    <div class="field smalltoken">
      <%= f.label :plNounClassMorpheme, "Plural noun class morpheme" %><br />
      <%= f.text_field :plNounClassMorpheme %>
    </div>
    <div class="field" style="display: none;">
      <%= f.label :plNounClassNumber %><br />
      <%= f.text_field :plNounClassNumber %>
    </div>
    <div class="field token">
      <%= f.label :root %><br />
      <%= f.text_field :root %>
    </div>
    <div class="field basicWord">
      <%= f.label :basicWord, "Is this a basic word? (E.g. Swadesh list word)" %><br />
      <%= f.check_box :basicWord %>
    </div>
  </div>
  <div class="grouping">
      <div class="field token" style="display: none;">
        <%= f.label :token %><br />
        <%= f.text_field :token %>
      </div>
      <div class="field bigtoken">
        <%= f.label :gloss %><br />
        <%= f.text_field :gloss %>
      </div>
      <div class="field">
        <%= f.label :pos, "Part of Speech" %><br />
        <%= f.select(:pos, options_for_select(Lexeme.partsOfSpeech.map{ |s| [s,s]})) %>
      </div>
      <div class="field">
        <%= f.label :classOrGroup, "Was this in class or in small groups?" %><br />
        <%= f.select(:classOrGroup, options_for_select([["Group","g"], ["Class","c"],])) %>
      </div>
  </div>
  <div class="grouping ifNoun" style="display: none;">
    <div class="field token"> <!-- eventually, based on POS selection, hide/show these -->
      <%= f.label :sgTranscription, "Singular Transcription" %><br />
      <%= f.text_field :sgTranscription %>
    </div> 
    <div class="field token">
      <%= f.label :plTranscription, "Plural Transcription" %><br />
      <%= f.text_field :plTranscription %>
    </div>
  </div>
  <div class="grouping ifVerb" style="display: none;">
    <div class="field">
      <%= f.label :tense, "Tense" %><br />
      <%= f.select(:pos, options_for_select(Lexeme.tenses.map{ |s| [s,s]})) %>
    </div>
  </div>
  <div class="field bigtext">
    <%= f.label :additionalForms, "Additional Forms (comma separated)" %><br />
    <%= f.text_area :additionalForms %>
  </div>
  <div class="field">
    <%= label_tag :audio, "Link to Audio File" %><br />
    <%= select_tag(:audio, options_from_collection_for_select(Audio.all, :id, :description), {:include_blank => true}) %>
    <%= link_to "Add New Audio", new_audio_path, :popup => true %>
  </div>
  <div class="field bigtext">
    <%= f.label :notes, "Any notes. (e.g. time of utterance in recording, tags)" %><br />
    <%= f.text_area :notes %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/lexemes/edit.html.erb
<h1>Editing lexical item</h1>

<%= render 'form' %>

<%= link_to 'Show', @lexeme %> |
<%= link_to 'Back', lexemes_path %>

app/views/lexemes/index.html.erb
<h1>Listing lexemes</h1>
<%= link_to 'New Lexeme', new_lexeme_path %>
<br />
<table id="lexemes_index" class="lexemestable">
    <thead>
    <th>Root</th>
    <th>Sg. NC</th>
    <th>Pl. NC</th>
    <th>Sg. Token</th>
    <th>Pl. Token</th>
    <th>Gloss</th>
    <th>POS</th>
    <th style="display: none;">Token</th>
    <!--<th>Sg. Noun Class #</th>-->
    <!--<th>Pl. Noun Class #</th>-->
    <th>Class/ Group</th>
    <th style="display: none;">Transcription</th>
    <th>Date</th>
    <th style="display: none;">Inf.Transcription</th>
    <th>Submitter</th>
    <th></th>
    <th></th>
    <th></th>
  </thead>

<% @lexemes.each do |lexeme| %>
  <tr>
    <td><%= lexeme.root %></td>
    <td><%= lexeme.sgNounClassMorpheme %></td>
    <td><%= lexeme.plNounClassMorpheme %></td>
    <td><%= lexeme.sgTranscription %></td>
    <td><%= lexeme.plTranscription %></td>
    <td><%= lexeme.gloss %></td>
    <td><%= lexeme.pos %></td>
    <td  style="display: none;"><%= lexeme.token %></td>
    <!--<td><%= lexeme.sgNounClassNumber %></td>-->
    <!--<td><%= lexeme.plNounClassNumber %></td>-->
    <td><%= lexeme.classOrGroup %></td>
    <td style="display: none;"><%= lexeme.transcription %></td>
    <td><%= lexeme.editDate.strftime("%m/%d/%Y") %></td>

    <td style="display: none;"><%= lexeme.infTranscription %></td>
    <td><%= lexeme.user.displayname or lexeme.user.email %></td>
    <td><%= link_to 'Show', lexeme %></td>
    <td><%= link_to 'Edit', edit_lexeme_path(lexeme) %></td>
    <td><%= link_to 'Destroy', lexeme, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Lexeme', new_lexeme_path %>

app/views/lexemes/new.html.erb
<h1>New lexical item</h1>

<%= render 'form' %>

<%= link_to 'Back', lexemes_path %>

app/views/lexemes/search.html.erb
<h3>Matches</h3>
<span id="yousearchedfor">You searched for: <span id="searchterm"><%= @regex %></span></span>
<% if !@matches.nil? #and @matches.size != 0 %>
<table id="lexemes_searchresults" class="lexemestable">
    <thead>
    <th>Root</th>
    <th>Sg. NC</th>
    <th>Pl. NC</th>
    <th>Sg. Token</th>
    <th>Pl. Token</th>
    <th>Gloss</th>
    <th>POS</th>
    <th style="display: none;">Token</th>
    <th>Owner</th>
    <th></th>
    <th></th>
    <th></th>
    </thead>
    <% @matches.each do |lexeme| %>
    <tr>
    <td><%= lexeme.root %></td>
    <td><%= lexeme.sgNounClassMorpheme %></td>
    <td><%= lexeme.plNounClassMorpheme %></td>
    <td><%= lexeme.sgTranscription %></td>
    <td><%= lexeme.plTranscription %></td>
    <td><%= lexeme.gloss %></td>
    <td><%= lexeme.pos %></td>
    <td style="display: none;"><%= lexeme.token %></td>
    <td><%= lexeme.user.email if lexeme.user %></td>
    <td><%= link_to 'Show', lexeme %></td>
    <td><%= link_to 'Edit', edit_lexeme_path(lexeme) %></td>
    <td><%= link_to 'Destroy', lexeme, confirm: 'Are you sure?', method: :delete %></td>
    </tr>
    <% end %>
</table>
<% else %>
    <span> There's nothing here!</span>
<% end %>

app/views/lexemes/searchform.html.erb
<h1>Search</h1>
<%= form_tag("/lexemes/search", :method => "get") do %>
  <%= label_tag(:regex, "Regex search:") %>
  <%= text_field_tag(:regex) %>
  <%= submit_tag("Search") %>
  <% fields = [
    ["Token", :token],
    ["Gloss", :gloss],
    ["P.O.S.", :pos],
    ["Root", :root],
    ["Sg. Noun Class Morpheme", :sgNounClassMorpheme],
    ["Pl. Noun Class Morpheme", :plNounClassMorpheme],
    ["Class/Group", :classOrGroup],
    ["User", :user],
    ["Date", :editDate],
    ["Additional Forms", :additionalForms],
    ["Notes", :notes],] %>
  <%= select_tag(:field, options_for_select(fields)) %>
<% end %>

app/views/lexemes/show.html.erb
<p>
  <b>Token:</b>
  <%= @lexeme.token %>
</p>

<p>
  <b>Gloss:</b>
  <%= @lexeme.gloss %>
</p>

<p>
  <b>Pos:</b>
  <% link = "http://linguistics-ontology.org/gold/2010/" + Lexeme.translateToGold(@lexeme.pos) %> 
  <a href="<%= link %>"> <%= @lexeme.pos %></a>
</p>

<p>
  <b>Root:</b>
  <%= @lexeme.root %>
</p>

<p>
  <b>Sgnounclassmorpheme:</b>
  <%= @lexeme.sgNounClassMorpheme %>
</p>

<p>
  <b>Sgnounclassnumber:</b>
  <%= @lexeme.sgNounClassNumber %>
</p>

<p>
  <b>Plnounclassmorpheme:</b>
  <%= @lexeme.plNounClassMorpheme %>
</p>

<p>
  <b>Plnounclassnumber:</b>
  <%= @lexeme.plNounClassNumber %>
</p>

<p>
  <b>Classorgroup:</b>
  <%= @lexeme.classOrGroup %>
</p>

<p>
  <b>Transcription:</b>
  <%= @lexeme.transcription %>
</p>

<p>
  <b>Editdate:</b>
  <%= @lexeme.editDate %>
</p>

<p>
  <b>Sgtranscription:</b>
  <%= @lexeme.sgTranscription %>
</p>

<p>
  <b>Pltranscription:</b>
  <%= @lexeme.plTranscription %>
</p>

<p>
  <b>Inftranscription:</b>
  <%= @lexeme.infTranscription %>
</p>

<p>
  <b>Additionalforms:</b>
  <%= @lexeme.additionalForms %>
</p>

<p>
  <b>Notes:</b>
  <%= @lexeme.notes %>
</p>
<p>
  <b>Submitter:</b>
  <%= @lexeme.user.displayname or @lexeme.user.email %>
</p>

<% unless @lexeme.audio.nil? %>
    <p>
      <%= link_to "Audio", @lexeme.audio %>
    </p>
<% end %>

<%= link_to 'Edit', edit_lexeme_path(@lexeme) %> |
<%= link_to 'Back', lexemes_path %>

<h2>Comments</h2>
<%= render @lexeme.comments %>
<% if can? :create, Comment %>
  <h2>Add a comment:</h2>
  <%= render "comments/formlex" %>
<% end %>