config/routes.rb
Kikuria::Application.routes.draw do
  resources :audios

  get "static_pages/home"

  get "static_pages/search"

  get "static_pages/help"

  resources :comments

  devise_for :users
  resources  :users, :only => [:show]

  resources :lexemes, :syntagms do
    collection do
      get 'search'
      get 'searchform'
      get 'export_csv'
    end
    resources :comments
  end

    
  root :to => "static_pages#home"

end

app/models/syntagm.rb
# encoding: UTF-8

class Syntagm < ActiveRecord::Base
  belongs_to :user

  has_many :comments, :as => :commentable
  belongs_to :audio
  
  validates :token, :presence => true
  validates :gloss, :presence => true

  def toOrth(item) #for backwards compatibility
    return Lexeme.toOrth(item)
  end
  def toDisplayOrth(item, prefs)
    return Lexeme.toDisplayOrth(item, prefs)
  end
end

app/controllers/syntagms_controller.rb
# encoding: UTF-8

class SyntagmsController < ApplicationController

  load_and_authorize_resource


  # GET /syntagms
  # GET /syntagms.json
  def index
    @syntagms = Syntagm.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @syntagms }
    end
  end

  # GET /syntagms/1
  # GET /syntagms/1.json
  def show
    @syntagm = Syntagm.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @syntagm }
    end
  end

  def search
    @matches = []
    #@nonmatches = []
    regex = params[:regex]
    regex = regex.gsub("C", "[bcdghjklmnN9rRstwy]")
    regex = regex.gsub("V", "[aeiouEIOU]")

    fields = [params[:field]]
    if fields == ['all']
        fields = ['token', 'gloss', 'notes',]
    end
    
    Syntagm.all.each do |syntagm|
        regexp = Regexp.new(syntagm.toOrth(regex))
        fields.each do |field|
            @matches << syntagm if regex.match(syntagm[field]) and !@matches.include?(syntagm)
        end
        #@nonmatches << syntagm unless Regexp.new(params[:regex]).match(syntagm.token)
    end
    
    respond_to do |format|
      format.html # search.html.erb
      format.json { render json: @syntagm }
    end
  end

  # GET /syntagms/new
  # GET /syntagms/new.json
  def new
    @syntagm = Syntagm.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @syntagm }
    end
  end

  # GET /syntagms/1/edit
  def edit
    @syntagm = Syntagm.find(params[:id])
  end

  # POST /syntagms
  # POST /syntagms.json
  def create
    @syntagm = Syntagm.new(params[:syntagm])

    @syntagm.editDate = Time.now
    
    @syntagm[:token] = @syntagm.toOrth(@syntagm[:token])

    @syntagm.audio = Audio.find(params[:audio]) unless params[:audio].nil? or params[:audio] == ""

    current_user.syntagms << @syntagm

    respond_to do |format|
      if @syntagm.save
        format.html { redirect_to @syntagm, notice: 'Syntagm was successfully created.' }
        format.json { render json: @syntagm, status: :created, location: @syntagm }
      else
        format.html { render action: "new" }
        format.json { render json: @syntagm.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /syntagms/1
  # PUT /syntagms/1.json
  def update
    @syntagm = Syntagm.find(params[:id])

    @syntagm.editDate = Time.now
    
    @syntagm[:token] = @syntagm.toOrth(@syntagm[:token])

    @syntagm.audio = Audio.find(params[:audio]) unless params[:audio].nil? or params[:audio] == ""

    respond_to do |format|
      if @syntagm.update_attributes(params[:syntagm])
        format.html { redirect_to @syntagm, notice: 'Syntagm was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @syntagm.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /syntagms/1
  # DELETE /syntagms/1.json
  def destroy
    @syntagm = Syntagm.find(params[:id])
    @syntagm.destroy

    respond_to do |format|
      format.html { redirect_to syntagms_url }
      format.json { head :ok }
    end
  end

  # adapted from http://oldwiki.rubyonrails.org/rails/pages/HowtoExportDataAsCSV
  # and http://www.funonrails.com/2012/01/csv-file-importexport-in-rails-3.html
  def export_csv
    filename = "Kikuria_syntagms"    

    #this is required if you want this to work with IE		
    if request.env['HTTP_USER_AGENT'] =~ /msie/i
      headers['Pragma'] = 'public'
      headers["Content-type"] = "text/plain"
      headers['Cache-Control'] = 'no-cache, must-revalidate, post-check=0, pre-check=0'
      headers['Content-Disposition'] = "attachment; filename=\"#{filename}\""
      headers['Expires'] = "0"
    end

    syntagms = Syntagm.find(:all)
    csv_data = CSV.generate do |csv|
      csv << [ "token", "gloss", "grammatical", "classOrGroup", "notes", "editDate", "user_id", "created_at", "updated_at"]
      syntagms.each do |s|
        csv << [s.token, s.gloss, s.grammatical, s.classOrGroup, s.notes, s.editDate, s.user_id, s.created_at, s.updated_at]
      end
    end
    send_data csv_data,
      :type => 'text/csv; charset=iso-8859-1; header=present',
      :disposition => "attachment; filename=#{filename}.csv"
  end

end

app/helpers/syntagms_helper.rb
module SyntagmsHelper
end

app/views/syntagms/_form.html.erb
<%= form_for(@syntagm) do |f| %>
  <% if @syntagm.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@syntagm.errors.count, "error") %> prohibited this syntagm from being saved:</h2>

      <ul>
      <% @syntagm.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :token %><br />
    <%= f.text_field :token %>
  </div>
  <div class="field">
    <%= f.label :gloss %><br />
    <%= f.text_field :gloss %>
  </div>
  <div class="field">
    <%= f.label :grammatical %><br />
    <%= f.check_box :grammatical %>
  </div>
  <div class="field">
    <%= f.label :classOrGroup %><br />
    <%= f.text_field :classOrGroup %>
  </div>
  <div class="field">
    <%= f.label :notes %><br />
    <%= f.text_field :notes %>
  </div>
  <div class="field">
    <%= f.label :editDate %><br />
    <%= f.datetime_select :editDate %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.number_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/syntagms/_searchform.html.erb
<%= form_tag("/syntagms/search", :method => "get") do %>
  <div>
  <%= label_tag(:regex, "Regex search:") %>
  <%= text_field_tag(:regex) %>
  <%= submit_tag("Search") %>
  <% fields = [
    ["All", :all],
    ["Token", :token],
    ["Gloss", :gloss],
    ["Notes", :notes],] %>
  </div>
  <div>Search what? <%= select_tag(:field, options_for_select(fields)) %></div>
    <div>
    <%= check_box_tag(:grammatical_only) %>
    <%= label_tag(:grammatical_only, "Only grammatical phrases") %></div>

    <div><%= check_box_tag(:class, 1, true) %>
    <%= label_tag(:class, "Include tokens from class") %>
    <%= check_box_tag(:group, 1, true) %>
    <%= label_tag(:group, "Include tokens from small groups") %></div>

  <p>Type what you want to search for. Select the field you want to search (e.g. just the gloss, or everything, or whatever). You can also use the V and C placeholders for vowels and consonants, respectively</p>
<% end %>

app/views/syntagms/edit.html.erb
<h1>Editing phrase</h1>

<%= render 'form' %>

<%= link_to 'Show', @syntagm %> |
<%= link_to 'Back', syntagms_path %>

app/views/syntagms/index.html.erb
<h1>Listing syntagms</h1>

<table>
  <thead>
    <th>Token</th>
    <th>Gloss</th>
    <th>Classorgroup</th>
    <th>Notes</th>
    <th>Editdate</th>
    <th>Submitter</th>
    <th></th>
    <th></th>
    <th></th>
  </thead>

<% @syntagms.each do |syntagm| %>
  <tr>
    <td><%= "*" unless syntagm.grammatical %> <%= syntagm.token %></td>
    <td><%= syntagm.gloss %></td>
    <td><%= syntagm.classOrGroup %></td>
    <td><%= syntagm.notes %></td>
    <td><%= syntagm.editDate %></td>
    <td><%= syntagm.user.displayname or syntagm.user.email %></td>
    <td><%= link_to 'Show', syntagm %></td>
    <td><%= link_to 'Edit', edit_syntagm_path(syntagm) %></td>
    <td><%= link_to 'Destroy', syntagm, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Syntagm', new_syntagm_path %>

app/views/syntagms/new.html.erb
<h1>New phrase</h1>

<%= render 'form' %>

<%= link_to 'Back', syntagms_path %>

app/views/syntagms/search.html.erb
<h3>Matches</h3>
<span id="yousearchedfor">You searched for: <span id="searchterm"><%= @regex %></span></span>
<% if !@matches.nil? #and @matches.size != 0 %>
<table id="lexemes_searchresults" class="lexemestable">
  <thead>
    <th>Token</th>
    <th>Gloss</th>
    <th>Grammatical</th>
    <th>Classorgroup</th>
    <th>Notes</th>
    <th>Editdate</th>
    <th>Submitter</th>
    <th></th>
    <th></th>
    <th></th>
  </thead>

<% @matches.each do |syntagm| %>
  <tr>
    <td><%= syntagm.token %></td>
    <td><%= syntagm.gloss %></td>
    <td><%= syntagm.grammatical %></td>
    <td><%= syntagm.classOrGroup %></td>
    <td><%= syntagm.notes %></td>
    <td><%= syntagm.editDate %></td>
    <td><%= syntagm.user.displayname or syntagm.user.email %></td>
    <td><%= link_to 'Show', syntagm %></td>
    <td><%= link_to 'Edit', edit_syntagm_path(syntagm) %></td>
    <td><%= link_to 'Destroy', syntagm, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>
<% else %>
    <span> There's nothing here!</span>
<% end %>

app/views/syntagms/searchform.html.erb
<h1>Search</h1>
<%= render 'searchform' %>

app/views/syntagms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Token:</b>
  <%= "*" unless @syntagm.grammatical %> <%= @syntagm.token %>
</p>

<p>
  <b>Gloss:</b>
  <%= @syntagm.gloss %>
</p>

<p>
  <b>Classorgroup:</b>
  <%= @syntagm.classOrGroup %>
</p>

<p>
  <b>Notes:</b>
  <%= @syntagm.notes %>
</p>

<p>
  <b>Editdate:</b>
  <%= @syntagm.editDate %>
</p>

<p>
  <b>Submitter:</b>
  <%= @syntagm.user.displayname or @syntagm.user.email %>
</p>

<% unless @syntagm.audio.nil? %>
    <p>
      <%= link_to "Audio", @syntagm.audio %>
    </p>
<% end %>


<%= link_to 'Edit', edit_syntagm_path(@syntagm) %> |
<%= link_to 'Back', syntagms_path %>

<h2>Comments</h2>
<%= render @syntagm.comments %>
<% if can? :create, Comment %>
  <h2>Add a comment:</h2>
  <%= render "comments/formsyn" %>
<% end %>